/*
 * myCBR License 2.0
 *
 * Copyright (c) 2009
 * Thomas Roth-Berghofer, Armin Stahl & Deutsches Forschungszentrum f&uuml;r K&uuml;nstliche Intelligenz DFKI GmbH
 * Further contributors: myCBR Team (see http://mycbr-project.net/contact.html for further information 
 * about the myCBR Team). 
 * All rights reserved.
 *
 * myCBR is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Since myCBR uses some modules, you should be aware of their licenses for
 * which you should have received a copy along with this program, too.
 * 
 * endOfLic */

package test.junittest.load;

import de.dfki.mycbr.core.Project;
/**
 * tests the import functionality of XML files generated by myCBR v2.6.4 to < v3.0
 * 
 * @author myCBR Team
 * 
 */
public class Test1000 {
	
	public static void main(String args[]) {
		try {
			Project p = new Project(System.getProperty("user.dir") + "/src/test/projects/Test30000/test30000_CBR_SMF.XML");
			while (p.isImporting()) {
			    for (int i = 0; i<10000;i++) {
			        System.out.println("Imported " + p.getCurrentNumberOfCases() + " of " + p.getTotalNumberOfCases() + " cases");
			    }
			}
//		Concept car = project.getConceptByID("Car");
//		Retrieval r = new Retrieval(car);
//		SequentialRetrieval sr = new SequentialRetrieval(project,r);
//		double total = 0;
//		for(int i =0; i<1000; i++) {
//			Date start = new Date();
//			sr.retrieve((DefaultCaseBase) project.getCaseBases().values().iterator().next(), car.getInstance("Car_5521"));
//
//			Date end = new Date();
//			
//			long duration = end.getTime()
//			- start.getTime();
//	
//			SimpleDateFormat dateFormat = new SimpleDateFormat();
//			dateFormat.applyPattern("h:mm:ss");
//	
//			double dur = ((double) duration) / 1000;
//			DecimalFormat decFormat = new DecimalFormat("###,###,##0.000");
//			decFormat.format(dur);
//			
//			System.out.println(i + ": " + dur );
//			total += dur;
//		}
//		System.out.println("sdk avg: " + total/1000);
//		
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
